from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class HelpTopic:
    """One help topic: a short summary plus a comprehensive HTML body."""
    id: str
    title: str
    summary: str
    body: str


@dataclass(frozen=True)
class HelpSection:
    """A table-of-contents grouping of topic ids."""
    title: str
    topic_ids: tuple[str, ...]


# Pipeline stage id -> help topic id. Stages not listed have no topic.
_STAGE_TO_TOPIC = {
    "load": "getting-started",
    "crop": "crop",
    "background": "background",
    "color": "color",
    "deconvolution": "deconvolution",
    "ai_denoise": "ai_denoise",
    "stretch": "stretch",
    "recover_core": "recover_core",
    "levels": "levels",
    "curves": "curves",
    "saturation": "saturation",
    "green_fringe": "green_fringe",
    "noise_sharpen": "noise_sharpen",
    "local_contrast": "local_contrast",
    "star_reduction": "star_reduction",
    "enhancements": "enhancements",
    "export": "export",
}


def stage_topic_id(stage_id: str) -> str | None:
    """The help topic id for a pipeline stage id, or None if it has no topic."""
    return _STAGE_TO_TOPIC.get(stage_id)


def topic(topic_id: str) -> "HelpTopic | None":
    """Look up a topic by id; None if unknown."""
    return TOPICS.get(topic_id)


def _t(id: str, title: str, summary: str, body: str) -> HelpTopic:
    return HelpTopic(id, title, summary, body)


# --- The content ------------------------------------------------------------
# Beginner-friendly and concept-teaching. Every step topic follows the
# "What it does / How to use it / Tips" shape. Kept accurate to how the app
# actually behaves.

_TOPIC_LIST = (
    # ---- Getting started ----
    _t("getting-started", "Getting started",
       "Turn a stacked Seestar image into a finished picture, one guided step at a time.",
       "<h4>What it does</h4>"
       "<p>Nocturne takes the stacked <b>FITS</b> file your Seestar S30 Pro produces and walks "
       "you through finishing it — crop, remove gradients, colour, stretch, and polish — as a "
       "guided, one-step-at-a-time flow. Nothing is destructive: you can undo, redo, or jump "
       "back to any earlier step at any time, and nothing is written to disk until you export.</p>"
       "<h4>How to use it</h4>"
       "<ol>"
       "<li>Open <b>Settings</b> and point Nocturne at your <b>GraXpert</b> program (required) "
       "and, if you have them, <b>RC-Astro</b> and <b>ASTAP</b> (both optional — ASTAP powers "
       "<b>Plate Solve</b>). Use <b>Test</b> to confirm each works.</li>"
       "<li>Click <b>Open FITS</b> and pick a stacked master (or use <b>Stack</b> to build one "
       "from a folder of subs).</li>"
       "<li>Work left-to-right through the steps in the sidebar — or click any step to jump to "
       "it. The panel on the right holds that step's controls; this box explains what it does.</li>"
       "<li>When you're happy, finish at <b>Export</b>.</li>"
       "</ol>"
       "<h4>Tips</h4>"
       "<p>The histogram (top-right) and the log (bottom) show what each step changed. "
       "Mouse wheel zooms, drag pans, and <b>Before/After</b> in the toolbar compares any step.</p>"),

    # ---- Concepts ----
    _t("linear-vs-stretched", "Linear vs. stretched",
       "Raw data is 'linear' and looks black; stretching reveals the faint detail.",
       "<h4>The idea</h4>"
       "<p>Straight out of stacking, astro data is <b>linear</b>: almost all the interesting "
       "signal sits in a tiny range of very dark values (around 0.003 out of 1.0). On its own it "
       "looks nearly black. To see it, the brightness has to be <b>stretched</b> — the faint "
       "values pulled up so nebulosity and dust become visible.</p>"
       "<h4>Preview vs. real stretch</h4>"
       "<p>Nocturne's preview <i>always</i> auto-stretches the image just so you can see it — "
       "much like PixInsight's Screen Transfer Function. That's display-only: the data underneath "
       "is still linear. The <b>Stretch</b> step is what commits a real stretch to the data so it "
       "matches the preview. Steps after Stretch (Levels, Saturation, and the rest) need real "
       "stretched data — so if you skip Stretch, Nocturne applies a sensible default for you when "
       "you move on.</p>"
       "<h4>Why it matters</h4>"
       "<p>Gradient removal and deconvolution work best on <b>linear</b> data (before Stretch); "
       "tone and colour polishing work on <b>stretched</b> data (after). The pipeline is ordered "
       "to put each step where it belongs.</p>"),

    _t("dualband", "Dualband, narrowband & Ha/OIII",
       "Your Seestar's 'LP' filter is a dualband narrowband filter — why the frames look red, "
       "and the two tools that do something about it.",
       "<h4>The idea</h4>"
       "<p>The Seestar's <b>LP</b> filter is a <b>dualband</b> filter. Rather than passing all "
       "visible light it passes two narrow bands and blocks everything else: <b>Ha</b> (hydrogen, "
       "deep red) and <b>OIII</b> (oxygen, teal). Emission nebulae glow in precisely those two "
       "colours and most light pollution does not, which is why a filter sold as a light-"
       "pollution filter is really a narrowband one. Nebulae are usually far brighter in Ha, so "
       "the frames come out red. Nothing is wrong with them.</p>"
       "<h4>Two gases in three channels</h4>"
       "<p>The sensor still has an ordinary colour grid over it, so the two bands land on "
       "different pixels: Ha on the red ones, OIII on the green and blue ones. A dualband image "
       "is therefore not a colour photograph in the usual sense — it is two gas maps wearing red, "
       "green and blue. That is what makes it possible to pull the two apart again, and it is "
       "also why ordinary colour instincts (&quot;stars should be white, the sky should look "
       "natural&quot;) only take you so far here.</p>"
       "<h4>What is not possible: SHO</h4>"
       "<p>The classic <b>SHO</b> &quot;Hubble palette&quot; puts sulfur, hydrogen and oxygen in "
       "red, green and blue. A Seestar has no sulfur filter and cannot capture the third gas at "
       "all, so SHO is not offered anywhere in Nocturne — anything claiming to produce it from "
       "dualband data has invented the missing channel. Two-gas schemes are the honest fit, and "
       "they look excellent.</p>"
       "<h4>Route 1 — you have a master already</h4>"
       "<p>From <b>Stack</b>, or straight out of the Seestar app: process it as you would any "
       "image, and after the stretch use <b>Narrowband…</b> in the toolbar. It takes the two "
       "gases back out of the finished colour image — hydrogen from red, oxygen from green and "
       "blue — lifts the weak oxygen until it matches the hydrogen, and recolours with "
       "<b>HOO</b>, <b>Pseudo-SHO</b> or <b>Pseudo-bicolor</b>. Nothing to re-stack; this is the "
       "usual route.</p>"
       "<h4>Route 2 — you still have the raw subs</h4>"
       "<p><b>Ha/OIII…</b> in the toolbar builds a better starting point out of the subs "
       "themselves. It keeps the two gases apart from the beginning, stacking a hydrogen master "
       "and an oxygen master separately from the raw pixels before combining them, so less of "
       "the faint oxygen is lost along the way. It produces a <b>single</b> master that opens "
       "straight into Nocturne — not two files, and nothing to reassemble elsewhere. Process it "
       "normally and finish with Narrowband for the palette.</p>"
       "<p>Route 2 is worth the extra time when the target genuinely has oxygen in it — the Veil, "
       "the Rosette, the Heart, most planetary nebulae. For a target that is nearly all hydrogen, "
       "Route 1 gets you to the same place sooner.</p>"
       "<h4>The rest of the pipeline treats it as ordinary colour</h4>"
       "<p>There is no dualband switch, and there is deliberately no palette in <b>Auto "
       "Enhance</b> — it calibrates colour the same way for every image and stops there. So an "
       "auto-enhanced dualband image comes out red-gold rather than teal. That is expected: the "
       "palette is a look rather than a correction, so it stays a decision you make in the "
       "Narrowband dialog, watching the preview.</p>"
       "<h4>If you shot without the filter</h4>"
       "<p>The Seestar can also shoot with the plain clear filter, and the FITS header says which "
       "was in the light path — <b>LP</b> for the dualband filter, <b>IRCUT</b> for the clear "
       "one. Neither tool here is meant for IRCUT data: both read the red channel as hydrogen, "
       "which on broadband data it is not.</p>"),

    _t("step-order", "Why the step order matters",
       "Some steps belong on linear data, others after the stretch — the flow keeps them in order.",
       "<h4>The idea</h4>"
       "<p>Post-processing isn't arbitrary — each operation assumes the data is in a particular "
       "state. Getting the order right is most of what makes results predictable.</p>"
       "<h4>Before the stretch (linear)</h4>"
       "<p><b>Crop</b>, <b>Background</b> (gradient removal) and <b>Deconvolution</b> (sharpening) "
       "belong on linear data, before the image is stretched. Gradients and the telescope's blur "
       "are properties of the raw light, best corrected there.</p>"
       "<h4>After the stretch (display)</h4>"
       "<p><b>Levels</b>, <b>Saturation</b>, <b>Noise Reduction</b>, <b>Local Contrast</b>, "
       "<b>Star Reduction</b> and <b>Enhancements</b> are tone and colour polish — they work on "
       "the stretched image you can actually see. Nocturne enforces this ordering, and auto-"
       "stretches for you if you jump ahead, so a finishing step never lands on linear data.</p>"),

    _t("history", "Non-destructive history",
       "Every step is cached; undo, redo, and jump-back are instant and lossless.",
       "<h4>What it does</h4>"
       "<p>Nocturne remembers the result of every step. Nothing overwrites your original — the "
       "loaded image is always the untouched starting point, and each step stacks on top of it.</p>"
       "<h4>How to use it</h4>"
       "<ul>"
       "<li><b>Undo / Redo</b> (toolbar) step back and forward instantly.</li>"
       "<li><b>Before/After</b> compares the current step against the one before it.</li>"
       "<li>Click an earlier step in the sidebar to <b>jump back</b>; changing it re-runs only "
       "the steps from there onward.</li>"
       "<li><b>Reset</b> returns to the freshly-loaded image.</li>"
       "</ul>"
       "<h4>Tips</h4>"
       "<p>Because nothing is destructive, experiment freely — you can always step back. Data is "
       "only written to disk when you <b>Export</b>.</p>"),

    _t("readout", "Hover readout & clipping warning",
       "A pixel readout under your cursor, plus a warning when tones are clipping.",
       "<h4>What it does</h4>"
       "<p>Hover anywhere over the image and a small pill in the bottom-left corner reports the "
       "pixel underneath: its position, its <b>R G B</b> values (a single <b>V</b> for a mono "
       "image), and — for colour images — its <b>L</b> (a plain average of the three channels — "
       "the same brightness measure Curves and Levels work from). It hides itself during <b>Crop</b>, "
       "where you're framing rather than judging "
       "tone, and reappears on every step from there on.</p>"
       "<h4>The clipping line</h4>"
       "<p>From Stretch onward, a line under the histogram reports how much of the image is "
       "clipped — pushed all the way to black or white, where the detail is gone for good. It "
       "turns amber past a threshold calibrated on real Seestar stacks.</p>"
       "<p>It judges what <i>your editing</i> caused. An image that arrives already crushed — a "
       "re-imported export, or an upscaled copy — would otherwise sit amber from the first "
       "Stretch with nothing you could do about it. When that happens the line says so, for "
       "example \"0.9% shadows clipped (0.9% shadows on import)\", and stays calm until you "
       "add to it.</p>"
       "<p>Tick <b>Show clipping</b> to paint the affected pixels on the canvas — blue for "
       "crushed shadows, red for blown highlights — live, even mid-slider.</p>"
       "<h4>Why the numbers look tiny before Stretch</h4>"
       "<p>Before the <b>Stretch</b> step your data is still <b>linear</b> — almost all the signal "
       "sits around 0.003 out of 1.0 (see the Linear vs. stretched topic). Nocturne's preview always "
       "auto-stretches the image just so you can see it, but the pill reports the real number "
       "underneath, not the brightened pixel on screen — so pre-Stretch it shows four decimal places "
       "and tags the reading <b>linear</b>, a reminder that the value and the brightness you're "
       "looking at are two different things there. From Stretch onward the data itself matches what "
       "you see, so the tag disappears and two decimals are enough.</p>"
       "<h4>The clipping summary and overlay</h4>"
       "<p>From <b>Stretch</b> onward, the panel under the histogram also reports how much of the "
       "image is <b>clipped</b> — pushed all the way to pure black or pure white in the 8-bit image "
       "an export would produce — as a percentage of highlights and shadows, naming whichever "
       "channel is worst. Past a threshold the line turns amber as a warning. Tick <b>Show "
       "clipping</b> to paint the clipped pixels directly on the canvas — shadows in blue, "
       "highlights in red — live, even while you're dragging a Levels or Curves slider.</p>"
       "<h4>Tips</h4>"
       "<p>A scatter of red dots on stars is almost always their <b>saturated cores</b> — blown at "
       "capture, not something an edit did or can fix — so don't chase it away. On a Seestar master "
       "this is rarer than you'd expect: a typical stack comes out of Stretch with only a pixel or "
       "two blown, so a percentage that stays near zero there is normal, not luck. A solid "
       "<b>region</b> turning red or blue, on the other hand, means a real edit (a Levels white "
       "point pulled too far in, say) is crushing detail, and is worth backing off. The overlay and "
       "summary work on every step from Stretch on, so you can leave it ticked and watch it react "
       "as you work.</p>"),

    # ---- The steps ----
    _t("crop", "Crop, rotate & flip",
       "Trim the ragged stacking edges and frame your target.",
       "<h4>What it does</h4>"
       "<p>Removes the uneven edges left by stacking (where subs didn't fully overlap) and lets "
       "you frame, rotate, and flip the image.</p>"
       "<h4>How to use it</h4>"
       "<p>Drag the box to choose the keep-area, pick an aspect ratio if you want a standard "
       "shape, and use rotate / flip to orient the target. Apply to commit.</p>"
       "<h4>Tips</h4>"
       "<p>Crop early — later steps then work on your final framing, and gradient removal has a "
       "cleaner frame to model.</p>"),

    _t("background", "Background extraction",
       "Remove light-pollution gradients so the sky is even.",
       "<h4>What it does</h4>"
       "<p>Uses <b>GraXpert</b> to model and subtract the smooth glow of light pollution and "
       "sky gradients, leaving an even background so the real signal stands out.</p>"
       "<h4>Seeing what was removed</h4>"
       "<p>After it runs, tick <b>Show what was removed</b> to put the subtracted "
       "gradient on the canvas on its own. This is the check worth making: a "
       "smooth ramp, brighter toward one edge or corner, is sky-glow and means "
       "the step did its job. If instead you can see the SHAPE OF YOUR OBJECT in "
       "it — the galaxy's outer halo, the nebula's faint edges — then the model "
       "mistook your signal for sky and subtracted some of it. In the corrected "
       "image that only looks slightly flat; here it is obvious. If you see it, "
       "undo and try Light.</p>"
       "<p>Colour here is real: it means the gradient was stronger in one channel "
       "than the others, which is normal for light pollution — it is not a fault.</p>"
       "<p>The reading beside it — for example \u201c0.11% of the image's range\u201d — "
       "is how strong the gradient was before removal. A gradient is a small "
       "fraction of the full range even when it dominates what you see, which is "
       "why this view is brightened to show it at all.</p>"
       "<h4>How to use it</h4>"
       "<p><b>Strong</b> is the ordinary choice — it removes the whole gradient Nocturne modelled, "
       "and that is what almost every frame wants.</p>"
       "<p><b>Light</b> removes about half as much — same model, applied gently. Reach for it when "
       "your target FILLS the frame, such as a large galaxy like M31 or a nebula spanning most of "
       "the picture. The model can mistake an object's faint outer parts for sky and subtract the "
       "very thing you came for, and no later step puts that back. If Strong leaves your object "
       "looking flat or hollowed out at the edges, that is what happened: undo and try Light, and "
       "accept a little leftover gradient in exchange.</p>"
       "<h4>Tips</h4>"
       "<p>Don't be alarmed if the sky looks a little <b>redder</b> afterwards — that's expected. "
       "Light pollution is often bluish, so removing it leaves the naturally red nebulosity more "
       "prominent. The next step, <b>Color</b>, neutralises any residual cast. Needs GraXpert "
       "(set its path in Settings).</p>"),

    _t("color", "Color calibration",
       "Neutralise the sky background automatically.",
       "<h4>What it does</h4>"
       "<p>Samples your empty sky and neutralises any leftover colour cast so the background is a "
       "clean grey — <i>without</i> touching your nebula's real colour. It measures the sky "
       "itself (not the whole frame), so red or teal nebulosity is preserved rather than washed "
       "out. Optional green removal (SCNR) is there if a green tinge remains.</p>"
       "<h4>How to use it</h4>"
       "<p>The panel runs top to bottom in the order you'd actually work: <b>calibrate</b>, then "
       "<b>nudge to taste</b>, then <b>de-green</b> if you imported the image from elsewhere.</p>"
       "<p><b>1 — Calibrate.</b> Pick a <b>Method</b> and apply. <b>Sky balance</b> (the default) "
       "neutralises the sky cast automatically. <b>Photometric (SPCC)</b> instead calibrates "
       "colour against real star measurements — it identifies stars in the field and balances the "
       "channels to their catalogue colours, for a more scientifically-accurate white balance "
       "(best on a plate-solvable field).</p>"
       "<p><b>2 — Nudge.</b> <b>Green ←→ Magenta</b> and <b>Cool ←→ Warm</b> shift the overall "
       "colour, with a live preview as you drag. Both sit at 0 by default and change nothing "
       "until you move them; double-click either to re-centre it. Press <b>Apply Tint</b> to "
       "commit. They multiply the channels rather than clipping one, so the colour differences "
       "<i>between</i> stars survive — an orange star stays orange relative to a blue one.</p>"
       "<p>Seestar data tends to land slightly magenta. That's the camera, not the stacking: a "
       "single raw sub already shows it. If the image looks a touch purple, drag <b>Green ←→ "
       "Magenta</b> to the left.</p>"
       "<p><b>3 — Remove Green.</b> You'll usually <i>not</i> need this on your own stacks; it's "
       "mainly for images stacked in other software, which often arrive green. Use it only if "
       "stars or background still take on a green tinge. It has a <b>strength</b> dial with a "
       "live preview — start gentle and drag up only as far as the green needs; full strength can "
       "flatten real nebula colour, so a light touch usually wins.</p>"
       "<h4>Tips</h4>"
       "<p>This is the step that cleans up the colour left over after Background extraction. It's "
       "mainly for broadband/OSC data. Photometric (SPCC) needs enough stars to match, so it "
       "suits star-rich fields.</p>"
       "<p>Tint and Remove Green do different jobs. The tint <i>shifts</i> colour and keeps the "
       "relationships between stars; Remove Green <i>clamps</i> one channel, which removes a cast "
       "but flattens colour along with it. Reach for the tint first.</p>"),

    _t("ai_denoise", "AI Denoise",
       "Nocturne's own denoiser, trained on Seestar stacks. Runs before Stretch.",
       "<h4>What it does</h4>"
       "<p>Removes noise using a model trained here on Seestar data — no external "
       "tool needed, and a few seconds rather than minutes. It predicts the "
       "<b>noise</b> and subtracts it, so <i>light</i> is a genuinely gentler "
       "version of <i>strong</i> rather than a different operation.</p>"
       "<h4>How to use it</h4>"
       "<p>Pick <b>light</b>, <b>medium</b> or <b>strong</b> and Apply. Medium is "
       "the default because it removes noise down to the level a very deep stack "
       "would have; strong goes further than that, which looks cleaner but is "
       "smoother than the sky really is.</p>"
       "<h4>Why it sits here</h4>"
       "<p>Before Stretch, next to Deconvolution, because that is where it was "
       "trained. The Stretch reshapes tones based on each image's own statistics, "
       "and a model applied afterwards would meet a transformation it has never "
       "seen.</p>"
       "<h4>Tips</h4>"
       "<p>It is trained on the <b>S30 Pro</b>. On other cameras the step does "
       "nothing rather than guess. It is also new — compare against the "
       "before/after and trust your eyes over the default.</p>"),

    _t("deconvolution", "Deconvolution",
       "Sharpen stars and recover fine detail on the linear image, before stretch.",
       "<h4>What it does</h4>"
       "<p>Corrects the small blur every telescope adds, tightening stars and recovering fine "
       "detail. It runs on the <b>linear</b> image (before Stretch), which is where deconvolution "
       "works best. Uses <b>BlurXTerminator</b> if you have RC-Astro, or a free sharpening "
       "fallback otherwise.</p>"
       "<h4>How to use it</h4>"
       "<p>Pick <b>light</b>, <b>medium</b>, or <b>strong</b>. Apply.</p>"
       "<h4>Tips</h4>"
       "<p>The Seestar is undersampled (big pixels for its focal length), so keep this "
       "conservative — light or medium usually looks best. Strongest with RC-Astro installed.</p>"),

    _t("stretch", "Stretch",
       "Reveal faint detail by committing a real non-linear stretch.",
       "<h4>What it does</h4>"
       "<p>Applies the real, permanent stretch that turns the dark linear data into a visible "
       "image — pulling faint nebulosity and dust up out of the shadows.</p>"
       "<h4>How to use it</h4>"
       "<p>Use the aggressiveness slider: the middle roughly matches the preview you already see; "
       "higher reveals more faint signal (and more noise). Apply.</p>"
       "<h4>Tips</h4>"
       "<p>If you move past this step without stretching, Nocturne commits a sensible default "
       "stretch automatically so the later steps work.</p>"),

    _t("levels", "Levels",
       "Fine-tune black point, midtones, and white point against the histogram.",
       "<h4>What it does</h4>"
       "<p>Precise control over the tonal range: set where black begins (black point), adjust the "
       "midtones (gamma), and set the white point — read against the histogram top-right.</p>"
       "<h4>How to use it</h4>"
       "<p>Press <b>Auto</b> for a starting point, then adjust. Nudge the <b>black point</b> up "
       "to deepen the background; use <b>midtones</b> to brighten or darken the middle of the "
       "range; pull the <b>white point</b> in to lift highlights. Apply.</p>"
       "<h4>What Auto does</h4>"
       "<p>It sets a <b>black point only</b>, and deliberately leaves midtones and white point "
       "at 1.00. Stretch has already placed the background where it wants it, so re-brightening "
       "the midtones here would fight it and wash the image out; and the data already reaches "
       "white, so pulling the white point in would only clip star cores and cost you their "
       "colour. On a frame whose background already sits at the floor — a bright nebula filling "
       "the field — Auto may suggest a black point of 0.000, which means there is nothing safe "
       "to take.</p>"
       "<h4>Tips</h4>"
       "<p>Levels works on the <b>stretched</b> image — on still-linear data even a tiny black "
       "point would clip everything to black, so it must come after Stretch. Nocturne handles "
       "that ordering for you. Small black-point nudges go a long way.</p>"),

    _t("curves", "Curves",
       "Shape a tone curve to add midtone contrast.",
       "<h4>What it does</h4>"
       "<p>Bends the tones with a smooth curve. Add <b>contrast</b> in the middle by "
       "steepening the slope so the nebula gains punch, and set the <b>black and white "
       "points</b> with the two end handles.</p>"
       "<h4>How to use it</h4>"
       "<p>Click the curve to add a point, drag to move it, double-click to remove it. "
       "The faint histogram behind the grid shows where the sky and nebula sit — drop a "
       "point on the sky peak and leave it to pin the background, then lift the midtones. "
       "Or pick a <b>preset</b> for a starting point. Watch the live preview. Apply.</p>"
       "<h4>Presets</h4>"
       "<p>Every preset is measured against <i>your</i> image rather than being a fixed shape: "
       "each one finds the sky level first and pins it, so the background does not drift while "
       "the rest of the curve moves. <b>Add contrast</b> and <b>Strong contrast</b> steepen the "
       "midtones; <b>Lift faint</b> brings up the outer nebulosity; <b>Deepen sky</b> darkens "
       "the background without touching what is above it; <b>Tame highlights</b> pulls back "
       "bright cores.</p>"
       "<h4>A bigger editor</h4>"
       "<p>The panel is narrow, and a tone curve wants to be square. <b>Open large editor</b> "
       "gives you the curve at over three times the area with the live preview beside it — "
       "worth it for anything more delicate than a single point.</p>"
       "<h4>Black and white points</h4>"
       "<p>Drag the <b>bottom-left handle to the right</b> to set a black point: every tone "
       "darker than it becomes pure black, which deepens the sky. Drag the "
       "<b>top-right handle to the left</b> to set a white point, which brightens the "
       "highlights. Dragging those handles the other way — up from the bottom, or down "
       "from the top — lifts the blacks or holds the whites back instead.</p>"
       "<p>Go carefully with the black point. It is the quickest way to a clean-looking "
       "sky and also the quickest way to throw away the faintest outer nebulosity, which "
       "cannot be recovered afterwards.</p>"
       "<h4>Fine control</h4>"
       "<p>Click a point to select it — the numbers in the corner show its input and "
       "output — then use the <b>arrow keys</b> to nudge it one step at a time, or hold "
       "<b>Shift</b> for ten. One step is the smallest change the exported file can "
       "actually record, so this is as fine as the adjustment can meaningfully get.</p>"
       "<h4>Tips</h4>"
       "<p>Small moves go a long way. A steep curve can crush the faint outer nebulosity "
       "into the background — keep an eye on the dim detail as you pull.</p>"),

    _t("color_balance", "Colour Balance",
       "Shift the colour of one tonal range, inside a chosen band of brightness.",
       "<h4>What it does</h4>"
       "<p>Warms or cools part of the picture without touching the rest. The classic "
       "case is a galaxy: its arms are young blue stars and its core is old and "
       "golden, so pushing the arms bluer while leaving the core alone separates the "
       "two populations. It is a finishing tool — it appends to your history, so it "
       "never discards work you have already done, and you can run it twice with "
       "different settings.</p>"
       "<p><b>Your stars are never altered.</b> The tool separates them out, adjusts "
       "only the starless layer, and lays the untouched stars back on top.</p>"
       "<h4>Tone</h4>"
       "<p>Which brightnesses to act on: <b>shadows</b>, <b>midtones</b> or "
       "<b>highlights</b>. Midtones is the usual choice — it is where nebulosity and "
       "spiral arms live.</p>"
       "<p><b>Each range keeps its own three sliders.</b> Set the midtones, switch to "
       "highlights, set those, and both are applied together when you press Apply — "
       "the midtones are not forgotten while you are looking at the highlights. So you "
       "can warm the midtones and cool the highlights in a single adjustment, which is "
       "a common move on a galaxy: the arms and the core are different star "
       "populations and want pushing in different directions.</p>"
       "<p>The three ranges overlap smoothly rather than meeting at hard boundaries, "
       "and their weights always add up to one — so setting all three to full strength "
       "in the same direction is no stronger than setting one.</p>"
       "<h4>The three sliders</h4>"
       "<p>Each is a pair of opposites: <b>Cyan — Red</b>, <b>Magenta — Green</b> and "
       "<b>Yellow — Blue</b>. Drag toward the colour you want more of. Small moves go "
       "a long way; a fifth of the travel is a clearly visible change.</p>"
       "<p><b>Preserve luminosity</b> keeps the brightness exactly as it was and "
       "changes only the colour. Leave it on unless you specifically want the "
       "adjustment to lighten or darken as well.</p>"
       "<p><b>Strength</b> scales the whole adjustment, like a layer's opacity.</p>"
       "<h4>Limit to</h4>"
       "<p>This is what makes the tool precise: the adjustment only applies to a "
       "<b>band of brightness</b>, which you set with the two handles over the "
       "histogram. Everything darker or brighter than the band is left alone.</p>"
       "<p>The presets are starting points, measured from your own image rather than "
       "fixed numbers — a stretched sky sits wherever the stretch put it, so a fixed "
       "band would be meaningless. <b>Whole image</b> applies everywhere. "
       "<b>Bright areas</b> takes everything above the sky. <b>Midtones</b> takes the "
       "middle of the signal. <b>Object, not the core</b> takes the object but stops "
       "short of its brightest centre — the one to reach for on a galaxy. After "
       "picking a preset the handles stay yours to move.</p>"
       "<p>The <b>black-to-white bar</b> beneath the histogram is the scale the "
       "handles work on: black is the darkest parts of your picture at the left, "
       "white the brightest at the right. Slide the handles in from either end to "
       "narrow what gets adjusted.</p>"
       "<p><b>Feather</b> softens both edges of the band, so the adjustment fades in "
       "and out instead of leaving a visible seam.</p>"
       "<p><b>Invert</b> flips the selection, so everything OUTSIDE the band is "
       "adjusted and the band itself is left alone. The two handles can only describe "
       "one continuous range, so this is the only way to say things like \u201ceverything "
       "except the galaxy\u201d.</p>"
       "<p><b>Show the mask</b> lights the parts of your picture the adjustment will "
       "reach and dims everything else to a dark grey. Look at it. A mask you cannot "
       "see is a mask you cannot trust, and this is the quickest way to tell whether "
       "you have selected the thing you meant to — on a galaxy you should see the "
       "arms lit and the core dark, which is precisely the check worth making.</p>"
       "<p>Nothing is tinted a false colour, and that is deliberate: an astro frame "
       "is already full of red, so a coloured wash would invent something you could "
       "mistake for real signal. The lit areas are your own colours, untouched.</p>"
       "<h4>Tips</h4>"
       "<p>Work in two passes rather than one big move — cool the arms, apply, then "
       "warm the core with a second run. Each is separately undoable.</p>"),

    _t("saturation", "Saturation",
       "Mute or boost colour intensity.",
       "<h4>What it does</h4>"
       "<p>Adjusts overall colour intensity — from muted to vivid.</p>"
       "<h4>How to use it</h4>"
       "<p>Drag left to mute, right to boost; the centre is no change. Apply.</p>"
       "<h4>Tips</h4>"
       "<p>Gentle boosts look natural and bring out nebula colour; heavy boosts also amplify "
       "colour noise in the background, so go easy.</p>"),

    _t("green_fringe", "Remove Green Fringe",
       "Remove the green colour fringe around stars.",
       "<h4>What it does</h4>"
       "<p>Stars are never truly green, so a green fringe or halo around them is an "
       "artifact (chromatic aberration or debayering). It suppresses the green excess "
       "only in the region around stars, so the nebula and background colour are left "
       "untouched. With <b>StarXTerminator</b> (RC-Astro) the stars are cleanly split "
       "out first for the most precise result; without it, a built-in star detector "
       "finds the stars and de-greens around them in place.</p>"
       "<h4>How to use it</h4>"
       "<p>Raise <b>Strength</b> until the green fringe on the stars fades (0 = off). "
       "The star detection runs once when you enter the step, then the slider previews "
       "instantly. Works without RC-Astro; setting RC-Astro (StarXTerminator) in "
       "Settings gives a cleaner separation.</p>"
       "<h4>Tips</h4>"
       "<p>A little usually does it. Because only the stars are affected, you can be "
       "fairly aggressive without shifting the overall colour. Removing the green often "
       "leaves the star a touch blue — a perfectly natural star colour.</p>"),

    _t("noise_sharpen", "Noise Reduction",
       "Smooth grain without smearing detail.",
       "<h4>What it does</h4>"
       "<p>Reduces the grainy noise the stretch amplifies, using <b>NoiseXTerminator</b> "
       "(RC-Astro) or a free fallback.</p>"
       "<h4>How to use it</h4>"
       "<p>Choose <b>light</b>, <b>medium</b>, or <b>strong</b>. Apply.</p>"
       "<h4>Tips</h4>"
       "<p>Denoise after stretching (which is where the grain shows). Don't overdo it — too much "
       "smears fine structure and stars. Light is often enough on a well-stacked master.</p>"),

    _t("recover_core", "Recover Core",
       "Pull blown-out bright cores back so they show detail.",
       "<h4>What it does</h4>"
       "<p>Short exposures blow out the bright centre of targets like M42, M8 or a "
       "galaxy nucleus — after stretching it becomes a featureless white blob. "
       "Recover Core pulls those highlights back down and re-expands the structure "
       "hiding inside them, so the core shows swirls and detail instead of pure white.</p>"
       "<h4>How to use it</h4>"
       "<p>Drag <b>Strength</b> up until the core shows detail without looking flat or "
       "grey. 0 = off. Watch the live preview. Apply.</p>"
       "<h4>Tips</h4>"
       "<p>Only the brightest regions are affected — the sky and faint nebulosity are "
       "left alone. Recover Core brings back detail that is still hiding in a bright, "
       "compressed core; but if a core is completely clipped to pure white in the data "
       "there is nothing left to recover, and it simply stays white.</p>"),

    _t("local_contrast", "Local Contrast",
       "Add mid-scale depth so nebulosity pops.",
       "<h4>What it does</h4>"
       "<p>Boosts mid-scale structure — the difference between neighbouring regions — so "
       "nebulosity and dust gain depth and dimensionality.</p>"
       "<h4>How to use it</h4>"
       "<p>Pick <b>light</b>, <b>medium</b>, or <b>strong</b>. Apply.</p>"
       "<h4>Tips</h4>"
       "<p>Subtle usually wins — strong local contrast can look crunchy and exaggerate noise.</p>"),

    _t("star_reduction", "Star Reduction",
       "Shrink stars so nebulosity takes centre stage.",
       "<h4>What it does</h4>"
       "<p>Reduces the size and dominance of stars, so a busy star field stops competing "
       "with the nebula. With <b>StarXTerminator</b> (RC-Astro) the split is cleanest; "
       "without it, a built-in star detector is used instead.</p>"
       "<h4>How to use it</h4>"
       "<p>Choose <b>light</b>, <b>medium</b>, or <b>strong</b>. Apply.</p>"
       "<h4>Tips</h4>"
       "<p>Works without RC-Astro; RC-Astro gives a cleaner separation. A little goes a "
       "long way — over-reduction leaves an unnatural, starless-looking frame. It pairs "
       "well just before the Enhancements step.</p>"),

    _t("star_spikes", "Star Spikes",
       "Draw colour-matched diffraction spikes on the brightest stars.",
       "<h4>What it does</h4>"
       "<p>A refractor like the Seestar produces no diffraction spikes — the four-point flares "
       "many people associate with an astrophoto come from the vanes holding a reflector\u2019s "
       "secondary mirror. This tool draws them anyway: a four-arm cross on the brightest stars, "
       "tinted with each star\u2019s own colour, rising out of a small soft bloom at the core "
       "rather than a bare dot.</p>"
       "<p>The cross is <b>screen-blended</b>, so it can only add light and never darkens what "
       "is underneath, and crossing arms do not pile up into a hot spot at the centre. It is a "
       "purely artistic choice, which is why it lives in the toolbar rather than among the "
       "processing steps.</p>"
       "<h4>Before you open it</h4>"
       "<p>Star Spikes works on the <b>stretched</b> image and says so if you reach for it "
       "earlier. Leave it to the end of your edit — anything you do afterwards is working on a "
       "picture that already has spikes painted into it.</p>"
       "<p>The dialog finds the stars <b>once</b>, when it opens, keeping the hundred brightest. "
       "The sliders after that only redraw, which is why they answer instantly.</p>"
       "<h4>The four sliders</h4>"
       "<p><b>Length (off \u2192 long)</b> — default <b>0.00</b>, range 0.00 to 1.00. <b>The "
       "dialog opens with this at zero, which means no spikes at all.</b> Nothing is broken and "
       "nothing has failed to load; nothing has been drawn yet. Push Length up and the preview "
       "answers. At 1.00 the longest arm is about <b>8%</b> of your image\u2019s shorter side, "
       "and each star gets a share of that in proportion to how bright it is — so the brightest "
       "star in the frame carries the longest cross and the rest fall in behind it. An arm that "
       "would come out under a pixel long is skipped, so the very bottom of the slider does "
       "nothing visible.</p>"
       "<p><b>Intensity (faint \u2192 full)</b> — default <b>100%</b>, range 0 to 100%. The "
       "opacity of the whole spike layer. 100% is full strength; somewhere around half reads as "
       "a suggestion of spikes rather than a graphic laid over the photo. At 0% nothing is "
       "drawn.</p>"
       "<p><b>Number of stars</b> — default <b>6</b>, range 0 to 50. How many stars get a cross, "
       "counted from the brightest down. At 0 nothing is drawn, exactly as at Length 0.</p>"
       "<p><b>Rotation</b> — default <b>0\u00b0</b>, range 0 to 90\u00b0. Tilts the cross. It "
       "stops at 90\u00b0 because the four arms are 90\u00b0 apart: turn it the whole way and "
       "you are back at the picture you started with. 45\u00b0 gives an \u00d7 where 0\u00b0 "
       "gives a +.</p>"
       "<p>Double-click any slider to put it back to its default.</p>"
       "<h4>Applying</h4>"
       "<p><b>Apply</b> commits exactly what the preview shows, as one history step called Star "
       "Spikes, and closes the dialog. <b>Close</b> leaves without changing anything. Undo takes "
       "the spikes off again like any other step.</p>"
       "<p>Star Spikes is one of only two steps a <b>recipe cannot record</b> (Trim is the "
       "other). Save Recipe says so by name, and a Batch run of that recipe produces images "
       "without spikes. That is deliberate — a spike pattern chosen for one picture means "
       "nothing applied blind to a folder — but do not expect a batch to reproduce a finished "
       "look that included them.</p>"
       "<h4>Tips</h4>"
       "<p>Less is more: a few long spikes on genuinely bright stars look intentional, spikes on "
       "everything looks like a filter was switched on. Six stars is the default for that "
       "reason.</p>"
       "<p>Spikes land on <b>detected</b> stars, not where you point. If nothing appears at any "
       "setting, the image has no stars the detector recognises — a heavily star-reduced frame, "
       "or a tight crop of nebulosity with nothing bright in it, will come back empty however "
       "far you push the sliders.</p>"
       "<p>The colour is sampled from the star itself, so a blue star gets blue spikes. If a "
       "cross comes out a colour you did not expect, that is what is in the pixel — the "
       "Saturation and Colour Balance steps before it decided that, not this tool.</p>"),

    _t("narrowband", "Narrowband",
       "Recolour a dualband image so the oxygen shows as its own colour instead of "
       "disappearing under the hydrogen.",
       "<h4>What it does</h4>"
       "<p>A dualband image holds two gases in three channels: <b>Ha</b> (hydrogen) is the red "
       "channel, <b>OIII</b> (oxygen) is the green and blue ones. Ha is usually far the stronger, "
       "so an ordinary colour combine comes out orange and the oxygen is there but invisible. "
       "Narrowband separates the two, lifts OIII until it is statistically as strong as Ha, and "
       "rebuilds the picture from the pair — so oxygen finally reads as teal rather than as a "
       "faint grey haze.</p>"
       "<h4>Before you open it</h4>"
       "<p>It works on the <b>stretched</b> image and on colour data; on a linear image the "
       "toolbar asks you to stretch first. Leave it until your tone work is done, because it "
       "replaces the colour of everything it touches. It applies as an ordinary undoable step "
       "and is captured in Recipes and Batch like any other.</p>"
       "<h4>Palette</h4>"
       "<p><b>HOO</b> — the honest arrangement: hydrogen in red, oxygen in blue, and a green "
       "built from the two. Red-gold nebula, teal oxygen. Start here.</p>"
       "<p><b>Pseudo-SHO</b> — hydrogen drives red and green, oxygen drives blue, for the gold-"
       "and-teal &quot;Hubble&quot; look. Gold where Ha dominates, teal where OIII does.</p>"
       "<p><b>Pseudo-bicolor</b> — hydrogen in red and blue, oxygen in green: a magenta nebula "
       "with green oxygen. The most stylised of the three, and the one that separates the two "
       "gases most obviously.</p>"
       "<p>Classic <b>SHO</b> is not on the list because dualband data contains no sulfur to put "
       "in it. The pseudo palettes are arrangements of the two real signals, not a third gas "
       "invented from nothing.</p>"
       "<h4>OIII boost — the key control (default ×1.00)</h4>"
       "<p>How hard the oxygen is lifted. <b>×1.00 is not &quot;off&quot;</b>: the match to Ha "
       "has already been made at that setting, and it is the right place to start. Raise it "
       "toward ×2.00 when oxygen is genuinely present and still looks weak — the Veil, the "
       "Rosette, most planetary nebulae. Drop it below ×1.00 to pull the oxygen back down when "
       "the lift is mostly amplifying noise, which is what happens on a target that has little "
       "OIII to begin with.</p>"
       "<p>If your master came from <b>Ha/OIII extraction</b>, the oxygen was already matched to "
       "the hydrogen when the master was built. Start at ×1.00 and raise it sparingly, rather "
       "than from the setting a tutorial suggests for a plain dualband stack.</p>"
       "<h4>Green blend — HOO only (default 0.60)</h4>"
       "<p>What green is made of. At <b>0.00</b> green is pure oxygen: the classic HOO, coolest "
       "and most teal. Raising it mixes hydrogen into green where both gases are bright, warming "
       "the nebula from red toward gold.</p>"
       "<p><b>It does nothing in Pseudo-SHO or Pseudo-bicolor.</b> Those palettes have no blended "
       "green — one takes green straight from hydrogen, the other straight from oxygen — so the "
       "slider moves and the picture does not. That is the control being honest, not a bug.</p>"
       "<p>In HOO and Pseudo-SHO green is also capped at the average of red and blue, which is "
       "what stops a narrowband image drifting green. Pseudo-bicolor's green is the real oxygen "
       "signal, so it is left alone.</p>"
       "<h4>Protect background (default 40%)</h4>"
       "<p>How much of the dark sky keeps its original colour. The recolour is confined to the "
       "bright signal and faded out below it; a higher setting protects more. At <b>0%</b> the "
       "whole frame is recoloured including the empty sky — which is what has happened when a "
       "background turns teal or magenta on you. Raise it if the sky has taken on the palette; "
       "lower it if faint outer nebulosity is being left behind uncoloured.</p>"
       "<h4>Saturation (default 0.50)</h4>"
       "<p>0.50 is native — the colour exactly as the palette produced it. Below that drains "
       "toward grey; above it boosts, and the boost is weighted to the nebula midtones so it "
       "tapers away in the noisy background and in bright star cores.</p>"
       "<h4>Brightness (default ×1.00)</h4>"
       "<p>A midtone lift on the finished recolour. It is applied last, after everything else, so "
       "it keeps working even with Preserve lightness on.</p>"
       "<h4>Preserve lightness — off by default</h4>"
       "<p>Off, you get the combine as it comes out, which is usually brighter and livelier; that "
       "is why it is the default. On, the tonal structure of the image you brought in is put back "
       "afterwards and only the colour changes. Turn it on when the recolour has moved the "
       "brightness of your object in a way you did not want, and use Brightness to compensate "
       "if it lands dark.</p>"
       "<h4>Stars</h4>"
       "<p>With <b>StarXTerminator</b> (RC-Astro) configured in Settings, the stars are lifted "
       "off once when the dialog opens, only the starless nebula is recoloured, and the original "
       "stars are laid back on top — so they keep their natural white-to-gold colour instead of "
       "being dyed by the palette. Without it the whole image is recoloured and the dialog says "
       "so; the result is still usable, but star colour may look off.</p>"
       "<h4>The preview</h4>"
       "<p>The preview is a smaller copy for speed, and it already has the stars screened back "
       "on, so what you tune is what <b>Apply</b> gives you. <b>Reset</b> puts every control back "
       "to its default; double-clicking a single slider resets just that one.</p>"
       "<h4>Credit</h4>"
       "<p>Normalization concept and palette formulas by Bill Blanshan &amp; Mike "
       "Cranfield (PixInsight NarrowbandNormalization).</p>"),

    _t("enhancements", "Enhancements",
       "Targeted, tap-to-stack finishing moves for colour, stars, dust, and glow.",
       "<h4>What it does</h4>"
       "<p>A bank of eleven gentle finishing taps, grouped by what they touch:</p>"
       "<ul>"
       "<li><b>Colour boosts</b> — <b>Boost Red</b> (Ha), <b>Boost Cyan</b> (OIII), "
       "<b>Boost Blue</b>, <b>Boost Gold</b>: hue-selective saturation lifts.</li>"
       "<li><b>Vibrance</b> — a smart, oversaturation-resistant pop that lifts the muted colours "
       "more than the already-vivid ones.</li>"
       "<li><b>Star Colour</b> — brings out the natural colour of stars (blue-white through gold) "
       "using a star/starless split, so only the stars gain colour, not the nebula.</li>"
       "<li><b>Darken Sky</b> / <b>Lighten Sky</b> — shadow-masked background adjustments.</li>"
       "<li><b>Dark Structure</b> — adds definition to dust lanes and dark nebulae.</li>"
       "<li><b>Soft Glow</b> — a dreamy Orton-style bloom over the bright signal.</li>"
       "<li><b>Sharpen Nebulosity</b> — crisps up nebula structure only. It sharpens the "
       "starless layer under a signal mask and screens the stars back untouched, so stars "
       "cannot ring and the background noise is not amplified.</li>"
       "</ul>"
       "<h4>How to use it</h4>"
       "<p>Tap a button to apply one gentle nudge; tap again to stack more. Each tap is its own "
       "undoable step, so you can dial the effect in and back it off precisely.</p>"
       "<h4>Tips</h4>"
       "<p>The colour boosts are hue-selective — Boost Red only deepens red areas and leaves teal "
       "alone, and Boost Gold warms golden-brown dust lanes. The sky moves are shadow-masked, so "
       "they only touch the dark background and leave nebula and stars untouched. Star Colour "
       "and Sharpen Nebulosity take a moment on their first tap while they separate the stars. "
       "Sharpening is the easiest finishing move to overdo — one or two taps is usually right, "
       "and if the noise starts to look like texture you have gone too far. Dark Structure and "
       "Soft Glow are subtle by design — stack a few taps to taste.</p>"),

    _t("export", "Export",
       "Save your finished image.",
       "<h4>What it does</h4>"
       "<p>Writes the finished image to disk.</p>"
       "<h4>How to use it</h4>"
       "<p>Choose a format: <b>16-bit TIFF</b>, <b>PNG</b>, or <b>FITS</b>. Or export a "
       "<b>starless + stars</b> pair (two TIFFs) for compositing elsewhere — that needs "
       "RC-Astro. The stars image is <i>unscreened</i>, so recombine the two with a "
       "<b>Screen</b> blend to reconstruct the image exactly.</p>"
       "<p><b>Colour space.</b> Every export is tagged with the space it is in, so other "
       "programs show it exactly as you see it here. <b>sRGB</b> is the default and the right "
       "answer almost always: it is the space your screen shows and the one every browser "
       "assumes. Choose <b>Display P3</b> or <b>Adobe RGB</b> only if the program you are "
       "taking the file into works in that space — the picture then arrives without being "
       "converted, and later edits such as a saturation boost have more room before they "
       "clip.</p>"
       "<p>A wider space does <i>not</i> add colour. Your picture's colours stay exactly "
       "where they are; only the way they are written down changes. And a wider space is "
       "offered for 16-bit TIFF only: in an 8-bit PNG the same 256 steps have to cover more "
       "ground, which shows up as banding in smooth gradients — and astrophotographs are "
       "mostly smooth gradients.</p>"
       "<h4>Tips</h4>"
       "<p>TIFF and FITS preserve the most information for further editing; PNG is best for "
       "quick sharing. You can also export earlier in the flow (even a linear file) if you want "
       "a clean base to finish in another tool.</p>"
       "<p>If an export has ever looked different in another program than it did in Nocturne, "
       "an untagged file was the reason: with nothing to say what space it was in, the other "
       "program had to guess, and guessed its own. That cannot happen now.</p>"),

    # ---- Tools ----
    _t("tools", "External tools: GraXpert, RC-Astro & ASTAP",
       "GraXpert is free and required; RC-Astro and ASTAP are optional and add extra power.",
       "<h4>GraXpert (free, required)</h4>"
       "<p>Powers <b>Background extraction</b> (and, optionally, Noise Reduction). It's free — "
       "download it, then set its path in <b>Settings</b> and press <b>Test</b>.</p>"
       "<h4>RC-Astro (paid, optional)</h4>"
       "<p>Adds <b>BlurXTerminator</b> (deconvolution), <b>NoiseXTerminator</b> (noise), and "
       "<b>StarXTerminator</b> (the star/starless split behind Star Reduction, Star Colour, the "
       "nebula saturation boost, Remove Green Fringe, and the starless+stars export). "
       "Set its path in Settings and Test it.</p>"
       "<h4>ASTAP (free, optional)</h4>"
       "<p>A free plate-solver that powers <b>Plate Solve</b> — identifying the field and "
       "annotating it with catalogue objects, named stars, a compass, and a scale bar. It also "
       "helps the Photometric (SPCC) colour method. Download ASTAP and its star database, then "
       "set its path in Settings and Test it.</p>"
       "<h4>Do I need the optional tools?</h4>"
       "<p>No — every RC-Astro step has a built-in free fallback, so the whole app works without "
       "it; RC-Astro simply makes those steps noticeably better. ASTAP is only needed for plate "
       "solving/annotation. Nocturne isn't affiliated with any of these tools.</p>"),

    _t("auto-enhance", "Auto Enhance",
       "One tap runs a fixed, conservative plan on your cropped frame — as ordinary, editable "
       "steps.",
       "<h4>What it does</h4>"
       "<p>Runs a set plan of processing steps for you, starting from your cropped frame. It is "
       "not a black box and not a separate engine: each stage lands in your history as the same "
       "step you would have applied by hand, so you can go to it in the stepper afterwards and "
       "change it, or Undo them one at a time.</p>"
       "<p>The plan is deliberately cautious. It is a good finished picture and an excellent "
       "starting point — it is not the best your data can look.</p>"
       "<h4>Why the button is greyed out</h4>"
       "<p>Auto Enhance needs a <b>Crop</b>, and the crop has to come <i>first</i>. It works from "
       "your cropped frame so that your composition survives, and it checks for a crop at the "
       "very start of your history. Crop after you have already processed something and the "
       "button stays grey — undo back, crop, and it lights up. Hovering the greyed-out button "
       "says so: <i>crop your image first</i>.</p>"
       "<h4>What it runs, in order</h4>"
       "<p><b>Background</b> at <i>strong</i> — <b>only if GraXpert is set up in Settings</b>. "
       "With no GraXpert there is simply no background step, and nothing tells you at the "
       "moment it is skipped.</p>"
       "<p><b>Color</b> — <b>photometric</b> if ASTAP is set up (colour measured against "
       "catalogue stars), otherwise a plain sky-neutralise. Both aim at natural, white-balanced "
       "colour.</p>"
       "<p><b>Stretch</b> at <b>0.30</b>, gentler than the 0.50 the manual step defaults to. A "
       "conservative stretch leaves you room to push further; an aggressive one cannot be "
       "undone by later steps.</p>"
       "<p><b>Levels</b> — a black point measured off the stretched image (median minus 3.5 "
       "\u00d7 MAD), not a fixed number. Gamma and white are left alone.</p>"
       "<p><b>Saturation</b> at <b>0.50</b> with a light <b>0.20</b> nebula boost.</p>"
       "<p><b>Remove Green Fringe</b> at full strength.</p>"
       "<p><b>Noise Reduction</b> at <i>strong</i>, always. The engine follows what you have "
       "installed — NoiseXTerminator if RC-Astro is set up, else GraXpert\u2019s denoiser, else "
       "Nocturne\u2019s own. The <i>level</i> is fixed rather than judged from the image: "
       "measured on real Seestar masters, the noise reading did not separate a noisy stack from "
       "a clean one, so choosing per image was guesswork dressed up as cleverness.</p>"
       "<p><b>Local Contrast</b> at <b>0.15</b>, a light finishing pass.</p>"
       "<h4>What it deliberately leaves out</h4>"
       "<p>No <b>Deconvolution</b>, <b>Recover Core</b>, <b>Curves</b>, <b>Star Reduction</b> or "
       "<b>AI Denoise</b>. Each of those wants a judgement about this particular picture, and "
       "each can visibly damage it when guessed at. They are the obvious next things to try by "
       "hand once you have the auto result in front of you.</p>"
       "<p><b>No narrowband palette, ever.</b> Dualband data comes out of Auto Enhance in its "
       "natural red-gold, not the teal-and-gold HOO look — Auto Enhance does not look at your "
       "filter at all. If you wanted the palette, that is the <b>Narrowband</b> tool, and it is "
       "a separate decision by design rather than a detection that failed.</p>"
       "<h4>Reading the result — and the steps that are not there</h4>"
       "<p>When it finishes, the message says <b>how many steps it applied</b>. That number is "
       "worth a glance: with nothing installed the plan is <b>7</b> steps, and with GraXpert "
       "<b>8</b>.</p>"
       "<p>A stage that fails — an external tool that errors, a subprocess that will not start — "
       "is <b>skipped in silence</b>. The rest of the chain still runs and you still get a "
       "finished picture, but that picture had no background extraction or no denoise in it, and "
       "the only sign is a step count lower than you expected and a gap in the history list. If "
       "the result looks flatter or noisier than you hoped, count the steps before you blame "
       "your data.</p>"
       "<p>The message also names any of the free tools you are missing. Installing "
       "<b>GraXpert</b> is the single biggest improvement available to a default Auto "
       "Enhance.</p>"
       "<h4>Re-running it</h4>"
       "<p>Auto Enhance always starts from the crop, so running it again on an already-enhanced "
       "image means discarding what is there. It asks first — and your crop, rotation and flips "
       "are kept.</p>"
       "<p>Say yes and <b>the old processing is gone at that moment</b>, not when the run "
       "finishes: it is dropped from the history before the first stage starts, so Redo cannot "
       "bring it back and cancelling the run part-way leaves you sitting on the bare cropped "
       "image. If the edit you are replacing was worth anything, save the project first.</p>"
       "<h4>Tips</h4>"
       "<p>Treat it as the first draft. The stages are ordinary history entries: click the one "
       "you disagree with in the stepper, adjust it, and carry on from there.</p>"
       "<p>Undo takes the stages off one at a time, in reverse order — it is not one big "
       "undo.</p>"),

    _t("plate-solve", "Plate Solve & Annotate",
       "Identify the field and label what's in it.",
       "<h4>What it does</h4>"
       "<p>Works out exactly where your image is pointing by matching its star pattern against "
       "a catalogue, then overlays what is there: deep-sky objects drawn at their true size on "
       "the sky, named stars, an RA/Dec grid, a north compass and a scale bar.</p>"
       "<h4>Before you start</h4>"
       "<p>Plate solving needs <b>ASTAP</b> <i>and its star database</i> — the database is a "
       "separate download from ASTAP itself, and a missing one is much the most common reason "
       "a solve fails. Set the ASTAP path in <b>Settings</b>; the toolbar button stays greyed "
       "out until you have.</p>"
       "<h4>How to use it</h4>"
       "<p>Press <b>Plate Solve</b> to open the tool, then <b>Solve</b>. Nothing runs until you "
       "press it, because a solve takes several seconds and spawns ASTAP. Afterwards the "
       "solution is remembered, and <b>Re-solve</b> forces a fresh one if you suspect it.</p>"
       "<p>Tick the layers you want — objects, named stars, RA/Dec grid, compass, scale bar, and "
       "<b>Colour by type</b> — and set <b>Density</b> for how crowded the labels may get.</p>"
       "<h4>Objects in field</h4>"
       "<p>The list beside the image is everything the solve found, deep-sky objects first and "
       "named stars below with their magnitudes. Click a row to jump the view to that object. "
       "It shows the whole field, including objects Density leaves off the image — so the ones "
       "hardest to spot are the easiest to reach. It follows the <b>Annotations</b> button, and "
       "its own ✕ hides it if you would rather see the picture.</p>"
       "<h4>Tips</h4>"
       "<p>Solve <b>early</b>, while the stars are crisp. The solution stays valid through every "
       "tonal step — stretching, denoising and star reduction change pixel values but do not "
       "move stars — so you solve once and keep the labels up for the rest of the edit.</p>"
       "<p>Cropping, rotating, flipping or trimming <i>does</i> change the framing, so the "
       "solution no longer lines up and its annotations are hidden. Nocturne says so when it "
       "happens; just solve again.</p>"
       "<p>The <b>Annotations</b> button on the image shows and hides the overlay without "
       "closing the tool. At Export, tick <b>Burn annotations</b> to render them into a PNG at "
       "full resolution, and exported FITS carry the solution as a WCS header.</p>"
       "<p>A solve is also what makes photometric colour calibration possible — it is how "
       "Nocturne finds real catalogue stars in your frame to correct colour against.</p>"),

    _t("share", "Share",
       "Reframe and caption a copy for social, without touching your master.",
       "<h4>What it does</h4>"
       "<p>Makes a version of your image ready to post somewhere — reframed to a common aspect "
       "ratio, with a caption burned in — while leaving your edited master untouched.</p>"
       "<h4>How to use it</h4>"
       "<p>Click <b>Share</b>, pick an aspect (or drag the crop box to frame it by eye), then "
       "<b>Export…</b> a file or <b>Copy to clipboard</b> to paste straight into a post.</p>"
       "<h4>The caption is yours</h4>"
       "<p>Nocturne writes a first draft from the image's own data — target, integration time, "
       "frame count, and your @handle from Settings — but it is an ordinary text field. Rewrite "
       "it, trim it to just the target, or say something the metadata never knew. The <b>↺</b> "
       "button restores the generated line.</p>"
       "<p>Put it <b>on the image</b> (a translucent band across the bottom) or <b>below</b> it, "
       "which extends the canvas so nothing you photographed is covered. Choose left, centred "
       "or right, one of three sizes, any colour, and how dark the band behind it is. The "
       "styling is remembered between shares; the text starts fresh for each image.</p>"
       "<h4>Size and format</h4>"
       "<p>Export at 1080, 2048 or 4096 px, or full size, as JPEG or PNG. Sizes only ever scale "
       "<i>down</i> — asking for more than you have will not invent detail — and the status line "
       "reports the pixel size actually produced.</p>"
       "<h4>Tips</h4>"
       "<p>Choose <b>PNG</b> when the image carries annotations or a caption at a small size: "
       "labels and text are hard edges, which is exactly what JPEG softens. <b>JPEG</b> is "
       "better for a plain photograph.</p>"
       "<p>If the frame has been plate-solved, a checkbox switches between the clean and the "
       "annotated image, so a labelled picture still gets the reframing and caption. With "
       "annotations on, the caption defaults to sitting below the image, where it cannot cover "
       "a label.</p>"
       "<p>The colour picker has an eyedropper — lift a colour straight out of the image you "
       "are captioning and the text belongs to the picture instead of sitting on top of it.</p>"
       "<p>Share needs a stretched image: it exports what you see, and a linear frame would come "
       "out black.</p>"),

    _t("upscale", "Upscale Crop",
       "Enlarge a region 2\u00d7 for a closer view — as a separate picture, not an edit.",
       "<h4>What it does</h4>"
       "<p>Takes a region of your finished image and rebuilds it at <b>twice the size</b>, so a "
       "small subject fills a frame of its own. It is a <b>derivative</b>, not a step: your open "
       "project is not touched by anything in this dialog.</p>"
       "<p>It is not a simple resize. Nocturne first separates the stars from everything else, "
       "enlarges the two layers apart, tightens the enlarged stars slightly so they stay points "
       "instead of growing into discs, and puts them back together. That is the whole reason the "
       "tool exists — a plain 2\u00d7 of the finished picture bloats every star.</p>"
       "<h4>How to use it</h4>"
       "<p>Stretch your image first; Upscale is greyed-out advice otherwise, because the star "
       "split has nothing to work with on linear data. Then click <b>Upscale Crop</b>.</p>"
       "<p>The left half shows your image with a <b>crop box</b> you can drag and resize, with "
       "no fixed aspect. Frame the subject, click <b>Upscale</b>, and the result appears on the "
       "right — the status line reports the new size in pixels. Leave the box alone and the "
       "whole frame is enlarged.</p>"
       "<p><b>Engine</b> currently offers one choice, <b>Lanczos</b>, a deterministic resample: "
       "it enlarges what was photographed and invents nothing. The dropdown is there because "
       "other engines are meant to join it; today there is nothing to decide.</p>"
       "<p>The scale is fixed at <b>2\u00d7</b>. Run it, and the button comes back when the "
       "result is ready — on a large crop the split and resample take a few seconds.</p>"
       "<p><b>Compare</b> is the honest before/after: it shows your original crop blown up to "
       "exactly the same size, so you are judging the upscale against the ordinary enlargement "
       "rather than against a smaller picture. Tick and untick it while looking at the stars.</p>"
       "<h4>Export, or Open as copy</h4>"
       "<p>Both buttons stay disabled until you have run <b>Upscale</b> once.</p>"
       "<p><b>Export\u2026</b> writes the enlargement to disk — JPEG, PNG or TIFF, offered as "
       "<i>yourfile_2x.jpg</i> by default — and drops a small <b>.txt</b> beside it recording "
       "the engine, the scale, the source, the target and the crop, ending "
       "\u201cpresentation derivative \u2014 enlarged, no synthesized detail\u201d. That "
       "sentence is the point of the file: it is what you can point at if anyone asks whether "
       "the detail is real.</p>"
       "<p><b>Open as copy</b> loads the enlargement back into the app as a <b>brand-new "
       "project</b>, and this is the part worth reading twice. It is not another step on your "
       "image. The upscaled picture arrives as though you had just opened a file: the stepper "
       "returns to Import &amp; assess, the log is cleared, and <b>your edit history is gone</b> "
       "— you cannot undo back across it, and the Provenance report of the new project starts "
       "here, with no record of the processing that produced it.</p>"
       "<p>So <b>save your project first</b> if there is any chance you will want to go back and "
       "adjust something. Export does not have this effect; only Open as copy replaces what you "
       "were working on.</p>"
       "<h4>Tips</h4>"
       "<p>Upscaling cannot invent detail that was never captured. It is for reframing tight on "
       "a subject that is sharp but small — not for rescuing something soft.</p>"
       "<p>With <b>StarXTerminator</b> installed and set in Settings, the star split is cleaner "
       "and so is the result; without it Nocturne uses its own free split, which is perfectly "
       "usable. Either way the stars themselves are always enlarged by the deterministic "
       "resample, whatever the engine dropdown eventually offers, because no engine should ever "
       "be allowed to invent a star.</p>"
       "<p>The crop is applied before the enlargement, so a tighter box is faster and no less "
       "detailed. Cropping afterwards in the new project throws away work already done.</p>"),

    _t("trim", "Trim",
       "Cut the edges off a finished image without losing your edit.",
       "<h4>What it does</h4>"
       "<p>Removes unwanted edges from the image you have already finished. Ragged stacking "
       "borders and smeared corners are often invisible in the linear data you cropped at the "
       "start, and only appear once you have stretched — by which point going back to "
       "<b>Crop</b> would discard every step you have done since.</p>"
       "<p>Trim is a finishing tool, not a pipeline step: it adds a final step at the end of "
       "your history rather than reaching back, so the whole edit survives and undo still "
       "works.</p>"
       "<h4>How to use it</h4>"
       "<p>Click <b>Trim</b> in the toolbar once your image is stretched. Drag the edges of the "
       "box to keep what you want — the size and how much you are removing are shown as you "
       "go — then <b>Apply Trim</b>.</p>"
       "<h4>Tips</h4>"
       "<p>The button stays greyed out until you have stretched, because before that there is "
       "no finished picture to trim and the <b>Crop</b> step is the better tool: cropping early "
       "means background extraction, Stretch and Levels all measure their settings on the part "
       "of the frame you actually kept.</p>"
       "<p>A trim changes the framing, so it clears a plate solve just as a crop does. Solve "
       "again afterwards if you want the annotations back.</p>"),

    _t("fullscreen", "Inspecting your image",
       "Press F for the image and nothing else.",
       "<h4>What it does</h4>"
       "<p>Press <b>F</b> and everything except the picture steps aside — toolbar, step list, "
       "right-hand panel and the log at the bottom. Useful when you want to judge noise, star "
       "shapes or faint detail without the interface competing for attention.</p>"
       "<h4>How to use it</h4>"
       "<p><b>F</b> to enter, <b>Escape</b> to come back. Zoom and pan work as usual: the wheel "
       "zooms, dragging pans, and the small zoom pill stays in the corner. <b>Fit</b> and "
       "<b>100%</b> in the toolbar are the quickest way to switch between the whole frame and "
       "true pixel scale.</p>"
       "<h4>Tips</h4>"
       "<p>Your zoom and position are kept when you enter and leave, so you can go full screen "
       "to look closely at something and return exactly where you were.</p>"
       "<p>Judge noise and sharpening at <b>100%</b>. At anything less the image is being "
       "resampled to fit the screen, which hides both.</p>"),

    # ---- Projects & records ----
    _t("saved-projects", "Saved Projects",
       "Save and reopen your whole editing session.",
       "<h4>What it does</h4>"
       "<p>Saves everything about your session — the image, your complete edit history, and any "
       "plate solve — into a single <b>.nocturne</b> file, so you can close Nocturne and later "
       "pick up exactly where you left off, with undo/redo intact.</p>"
       "<h4>How to use it</h4>"
       "<p><b>Save Project</b> (or <b>Save Project As…</b>) writes the file; <b>Open Project</b> "
       "reloads one; <b>Recent Projects</b> lists the last few. <b>Close Project</b> returns to "
       "the welcome screen.</p>"
       "<h4>Tips</h4>"
       "<p>Unlike Export — which writes a flat, finished picture — a project keeps every step "
       "editable. Saving runs in the background, so the app stays responsive.</p>"),

    _t("provenance", "Provenance report",
       "Export a readable record of everything you did.",
       "<h4>What it does</h4>"
       "<p>Writes a plain, readable <b>Markdown</b> record of your whole edit — every step and its "
       "settings, plus the capture details and the app version — so you, or anyone, can see "
       "exactly how the image was made.</p>"
       "<h4>How to use it</h4>"
       "<p>Open the <b>Project</b> menu ▸ <b>Provenance report…</b>, then <b>Save…</b> the report "
       "or <b>Copy to clipboard</b>.</p>"
       "<h4>Tips</h4>"
       "<p>Handy for reproducibility, sharing your process with others, or just remembering what "
       "worked on a particular target.</p>"),

    # ---- Stacking & Ha/OIII ----
    _t("stacking", "Stacking",
       "Build a master image from a folder of subs.",
       "<h4>What it does</h4>"
       "<p>Turns a folder of individual sub-exposures into a single clean <b>master</b>: it "
       "grades and rejects poor frames, registers (aligns) the rest — handling the field rotation "
       "an alt-az mount like the Seestar introduces — and integrates them.</p>"
       "<h4>How to use it</h4>"
       "<p>Click <b>Stack</b> in the toolbar and choose the folder of subs. Grading starts "
       "immediately — that is the slow part, because every frame is opened and measured. Your "
       "<b>Strictness</b> and <b>Integration</b> choices are applied afterwards and cost nothing, "
       "so you can change them freely without re-reading a single file.</p>"
       "<h4>Strictness — how much gets thrown away</h4>"
       "<p>Grading measures four things per frame: how many stars it can find, how big those "
       "stars are (<b>FWHM</b> — bigger means softer), how <b>round</b> they are, and how bright "
       "the sky is. Strictness decides where the line falls on the two star-shape measurements.</p>"
       "<p>Roundness is worth its own column. A gust of wind, a nudge of the tripod or a tracking "
       "slip stretches the stars into short streaks, and that damage cannot be undone later — but "
       "it barely moves the FWHM, because a star stretched one way and squeezed the other covers "
       "the same area. A frame can look perfectly sharp by the numbers and still be trailed, which "
       "is why the two are judged separately. <b>1.00</b> means circular; anything past about "
       "<b>1.3</b> is visibly streaked.</p>"
       "<p>The limit is set from the session itself, not a fixed number: Nocturne takes the "
       "typical frame and allows a margin above it. <b>Relaxed</b> allows a wide margin, "
       "<b>Normal</b> a moderate one, <b>Strict</b> a narrow one. So it is always relative to the "
       "night you actually had — a soft frame in a sharp session is rejected, while the same frame "
       "in a soft session is kept.</p>"
       "<p>Two rejections ignore the setting entirely. A frame with fewer than half the usual "
       "number of stars is dropped at every strictness — that is cloud, trailing or a bumped "
       "mount, and it is bad by any standard. A brighter-than-usual sky is only a warning, and "
       "the frame is kept.</p>"
       "<p>Start at Normal. Go Strict if you have plenty of frames and want the sharpest result; "
       "go Relaxed if you are short of data and would rather have the signal. You can always "
       "tick or untick individual frames by hand, and your manual choices survive a strictness "
       "change.</p>"
       "<p><b>If the count does not move when you change it</b>, that is informative rather than "
       "broken: it means the frames are consistent enough that none of them stand out from the "
       "rest. Strictness compares frames against each other, so a session that is uniformly "
       "mediocre has no outliers to find.</p>"
       "<h4>Integration — how the frames are combined</h4>"
       "<p><b>Sigma-clipped</b> looks at each pixel across all frames, discards values that "
       "disagree with the rest, and averages what is left. That is what removes satellite trails, "
       "aeroplanes and cosmic ray hits — anything present in a few frames but not the others. "
       "It is the right choice almost always.</p>"
       "<p><b>Average</b> simply adds every frame and divides. Marginally less noisy, and it "
       "keeps every photon, but anything that crossed your field stays in the picture, faintly. "
       "Use it when you have very few frames — clipping needs enough of them to tell a satellite "
       "from ordinary noise, and below roughly ten it has no basis for the judgement.</p>"
       "<p><b>κ</b> sets how far a pixel must stray before it is discarded. <b>Low</b> rejection "
       "keeps more and is safer for faint detail; <b>High</b> is more aggressive and better on a "
       "night full of satellites. Medium suits most sessions.</p>"
       "<h4>Framing — trim the ragged edges, or keep everything</h4>"
       "<p>An alt-az mount rotates the field as it tracks, so the frames do not stack in a "
       "perfect pile: the outer edges of the result are built from fewer frames than the middle. "
       "<b>Trim the ragged edges</b> cuts back to the part nearly every frame covered.</p>"
       "<p>Turn it off to keep the full frame. Those edge pixels are correctly exposed — they "
       "are simply noisier, because fewer frames went into them — and on a small sensor they are "
       "worth having. Nothing is lost either way: you can always crop later with the Crop step "
       "or Trim, but nothing can put back what the stacker threw away.</p>"
       "<h4>Mosaic — several pointings into one wide picture</h4>"
       "<p>The Seestar can shoot a <b>mosaic</b>: it points at a patch of sky, takes a "
       "run of frames, moves to the next patch, and so on. Ordinary stacking cannot "
       "combine those, because it aligns every frame against one reference frame and the "
       "far panels share no stars with it. Nocturne notices when your subs cover more "
       "than one pointing and offers <b>Stack as mosaic</b>, which says how many "
       "pointings it found.</p>"
       "<p>It stacks each pointing separately — grading, rejection and integration all "
       "work exactly as they do for a single field — then plate-solves each one to find "
       "out where it belongs on the sky, and assembles them onto one canvas. Because the "
       "positions come from the sky rather than from guesswork, the panels line up as "
       "well at the edges of the picture as in the middle.</p>"
       "<p>It needs <b>ASTAP</b>, which is what does the plate solving, and it takes "
       "considerably longer than one stack: each pointing is a stack in its own right, "
       "plus a solve. A twenty-panel mosaic is a coffee, not a moment. A pointing with "
       "only a frame or two is dropped and named in the report — that is usually the "
       "telescope slewing rather than data you meant to keep.</p>"
       "<p><b>Trim the ragged edges</b> applies here too, and matters more: the outline "
       "of a mosaic is genuinely ragged. Note also that a mosaic keeps its position on "
       "the sky, so Plate Solve can label the objects in it without solving again.</p>"
       "<h4>Tips</h4>"
       "<p>More subs mean a cleaner master with less noise. If you already have a stacked master "
       "(e.g. from the Seestar app), you can skip this and just Open FITS.</p>"
       "<p>Stack one session at a time where you can. A folder holding several nights, or mixed "
       "exposure lengths, is combined as though it were one — and a night that was out of focus "
       "will quietly soften the result. Because grading compares each frame against the others, "
       "a whole bad session is not an outlier and will not be caught.</p>"),

    _t("haoiii", "Ha / OIII extraction",
       "Stack a folder of raw subs into a master that keeps the oxygen separate from the "
       "hydrogen.",
       "<h4>What it does</h4>"
       "<p>This is a <b>stacker</b>, not a splitter: you point it at the same folder of raw subs "
       "you would hand to Stack, and it builds a different kind of master.</p>"
       "<p>Your dualband filter passes two colours of light — <b>Ha</b> (hydrogen, deep red) and "
       "<b>OIII</b> (oxygen, teal) — and the camera's colour grid catches them on different "
       "pixels: Ha on the red-filtered ones, OIII on the green and blue ones. Ordinary stacking "
       "debayers each sub into full colour first, which mixes the two together and leaves the "
       "weak oxygen buried under the hydrogen. Ha/OIII extraction keeps them apart the whole "
       "way: it pulls a Ha frame and an OIII frame out of every sub, aligns and stacks the two "
       "sets separately, lifts the faint OIII to the same brightness and contrast as the Ha, and "
       "packs them into one colour master with <b>Ha in red and OIII in green and blue</b>.</p>"
       "<p>That master is what a two-gas picture is made from. Process it normally, and use "
       "<b>Narrowband</b> after the stretch to turn it into HOO or a pseudo-palette.</p>"
       "<h4>How to use it</h4>"
       "<p>Click <b>Ha/OIII…</b> in the toolbar and choose your <b>Folder of raw subs</b>. "
       "Grading starts the moment you pick it — every <b>.fit</b>, <b>.fits</b> and <b>.fts</b> "
       "file directly inside that folder is opened and measured, and sub-folders are not "
       "searched. Then set <b>Integration</b>, check the <b>Output</b> path — it defaults to "
       "<b>HaOIII_master.fits</b> inside the same folder — and press <b>Extract</b>. The "
       "finished master opens in Nocturne as a linear image, ready for the ordinary steps, and "
       "the FITS is written to disk as well.</p>"
       "<h4>It needs raw subs — an already-stacked image will not do</h4>"
       "<p>The separation only exists before the sub is debayered, so this tool reads the raw "
       "one-plane frames straight off the camera. A master — from Stack, from the Seestar app, "
       "or from a previous run of this tool — has already been turned into three colour planes "
       "and cannot be taken apart again. Such a file is listed unticked as <b>Already-stacked "
       "image (not a raw sub)</b> and skipped.</p>"
       "<p>That is also why your own output appears in the list the second time round: the "
       "master is written into the folder it read, so the next grading pass finds it. It is "
       "rejected automatically — nothing to do.</p>"
       "<h4>The frame list</h4>"
       "<p>Each frame is graded exactly as it is for Stacking, and the table shows <b>Stars</b>, "
       "<b>FWHM</b> (star size — bigger means softer) and <b>Bg</b> (sky brightness). A frame "
       "arrives unticked when the grader rejected it: too few stars, stars softer than the rest "
       "of the session, stars trailed, or a file it could not measure. See the Stacking topic "
       "for what those judgements mean.</p>"
       "<p>There is no <b>Strictness</b> setting here — grading runs at the normal setting, and "
       "the tick boxes are yours to override. Untick anything you do not want, tick back "
       "anything you do. The best-graded frame becomes the reference every other frame is "
       "aligned to. You need at least three frames.</p>"
       "<h4>Integration</h4>"
       "<p>The same two methods as Stacking, applied to each gas in turn. <b>Sigma-clipped</b> "
       "throws away pixels that disagree across the frames, which is what removes satellite "
       "trails and cosmic rays; it is the right choice almost always. <b>Average</b> keeps every "
       "photon and is for when you have very few frames. <b>κ</b> sets how far a pixel may stray "
       "before it is discarded — <b>Low</b> rejection keeps more, <b>High</b> is more "
       "aggressive, Medium suits most sessions.</p>"
       "<p>Unlike Stacking there is no framing choice: the ragged edges an alt-az mount leaves "
       "are always trimmed back to the part nearly every frame covered.</p>"
       "<h4>Why it takes longer than a plain stack</h4>"
       "<p>Every sub is opened several times over — once to grade it, once to align it, and then "
       "again for each of the two channels, twice each under Sigma-clipped because clipping "
       "needs one pass to learn what is normal and a second to apply it. The progress line names "
       "the phase it is in (<b>grading</b>, <b>registering</b>, <b>stacking Ha</b>, <b>stacking "
       "OIII</b>). It is not stuck.</p>"
       "<h4>The result looks less red — that is the point</h4>"
       "<p>A plain stack of dualband subs is overwhelmingly red, because Ha is far the stronger "
       "signal. Here the OIII is matched to the Ha before the two are combined, so the master "
       "comes out much more neutral, with teal wherever oxygen genuinely outweighs hydrogen. "
       "Nothing has been invented — the oxygen was always there, at a level you could not "
       "see.</p>"
       "<p>One consequence worth knowing: the lift has already happened. When you reach "
       "<b>Narrowband</b>, leave <b>OIII boost</b> near ×1.00 to begin with and raise it only if "
       "the oxygen still looks weak, rather than starting from the setting a tutorial recommends "
       "for an ordinary dualband master.</p>"
       "<h4>Tips</h4>"
       "<p>If you only want a normal colour picture, use <b>Stack</b> — it is faster and simpler. "
       "Reach for Ha/OIII extraction when the target is an emission nebula with real oxygen in "
       "it (the Rosette, the Heart, the Veil, most planetary nebulae) and you want that oxygen "
       "to show as its own colour.</p>"),

    # ---- Recipes & Batch ----
    _t("recipes", "Recipes & Batch",
       "Save the steps you applied as a file, and replay them over a folder of masters.",
       "<h4>What it does</h4>"
       "<p>A <b>recipe</b> is the list of steps you applied, written out as a small "
       "<b>.json</b> file. <b>Batch</b> replays one recipe over a folder of masters without "
       "opening any of them, writing one finished file per input.</p>"
       "<p>They are two separate buttons and Batch does not touch the picture you have open — "
       "it reads from a folder on disk and writes to another one. You can run a batch with no "
       "image open at all.</p>"
       "<h4>Saving a recipe — and the two steps it cannot hold</h4>"
       "<p>Process one image the way you want it, then click <b>Save Recipe</b>. Everything in "
       "the stepper is recorded: Background, Color, Colour Tint, Remove Green, Deconvolution, "
       "AI Denoise, Stretch, Recover Core, Levels, Curves, Saturation, Remove Green Fringe, "
       "Noise Reduction, Local Contrast and Star Reduction — plus Crop, Rotate and Flip, the "
       "<b>Narrowband</b> and <b>Colour Balance</b> tools, and all ten <b>Enhancements</b> "
       "taps.</p>"
       "<p>Two steps cannot be recorded: <b>Star Spikes</b> and <b>Trim</b>. If either is in "
       "your history, Save Recipe stops first and names it — <i>this recipe can\u2019t "
       "include\u2026</i> — and you choose whether to save the rest anyway. That is not a "
       "failure. Both are placed by hand on one particular picture, and neither means anything "
       "applied blind to a different frame.</p>"
       "<h4>What a replayed crop actually does</h4>"
       "<p>This is the one that surprises people. A recipe keeps your <b>aspect ratio, rotation "
       "and flips</b> — it does not keep the box you dragged. On replay, each image is trimmed "
       "to <i>its own</i> detected content rectangle (the non-black area left after stacking) "
       "and then centre-cut to your aspect.</p>"
       "<p>Across a folder that is what you want: every frame loses its own ragged border rather "
       "than the one measured on some other frame. But it does mean a recipe cannot reproduce a "
       "composition. If the framing was the point, crop that image by hand.</p>"
       "<h4>Batch — the dialog</h4>"
       "<p><b>Recipe</b> is the .json you saved. <b>Input folder</b> is where the masters are, "
       "<b>Output folder</b> where the results go, and <b>Format</b> is TIFF, PNG or FITS. Then "
       "<b>Run</b>. The bar counts files, and the line under it reports the result.</p>"
       "<p><b>Only FITS is read.</b> Batch picks up <b>.fit</b>, <b>.fits</b> and <b>.fts</b> "
       "from the folder you chose — not from sub-folders, and not TIFF, PNG or JPEG whatever the "
       "recipe can write. Point it at a folder of TIFFs and it will report <i>Done — 0/0 "
       "succeeded</i>, which is the app telling you it found nothing, not that it did nothing "
       "wrong.</p>"
       "<p>Each result is named after its input — <b>m42.fits</b> becomes <b>m42.tiff</b> — and "
       "a file of that name in the output folder is overwritten without asking. <b>Give the "
       "output its own folder</b>: choosing FITS and pointing the output at the input folder "
       "writes m42.fits over m42.fits, and your master is gone.</p>"
       "<p><b>Cancel</b> stops between files. Anything already written stays, the file in flight "
       "is abandoned rather than finished (a running GraXpert or RC-Astro is killed outright), "
       "and the status line says how many were written before you stopped.</p>"
       "<p>One bad file does not end the run. Batch carries on and the summary names every file "
       "that failed and why, next to the count that succeeded.</p>"
       "<h4>When every file fails</h4>"
       "<p>Batch runs the same external tools the app does, per file, using the paths in "
       "<b>Settings</b>. If the recipe contains a <b>Background</b> step and GraXpert is not set "
       "up on the machine you are running it on, that step cannot be skipped — the file it is "
       "in fails, and since the recipe is the same every time, so does every other file. The "
       "message is an obscure one from the operating system rather than a helpful sentence. If "
       "a whole batch fails identically, check Settings before you suspect your data.</p>"
       "<h4>Tips</h4>"
       "<p>Recipes hold steps, not pixels — the file is a few kilobytes and you can keep, copy "
       "or send one.</p>"
       "<p>A batch is not quick. Every file gets the full chain, including a GraXpert background "
       "model and a denoise pass if the recipe asks for them, so twenty masters is a long run "
       "rather than a moment.</p>"
       "<p>Best used for the same target shot over several sessions, where one set of decisions "
       "genuinely suits every frame. A recipe made on a bright galaxy will not flatter a faint "
       "nebula.</p>"),

    # ---- Troubleshooting ----
    _t("troubleshooting", "Troubleshooting & FAQ",
       "Quick answers to the things people hit most.",
       "<h4>The image went black on Levels</h4>"
       "<p>Levels needs a <b>stretched</b> image; on linear data it clips to black. Stretch first "
       "— newer builds auto-stretch for you when you enter a finishing step.</p>"
       "<h4>The sky went red after Background</h4>"
       "<p>Expected. Background removed the bluish light pollution, leaving the naturally red "
       "nebulosity more prominent; the <b>Color</b> step neutralises the residual cast.</p>"
       "<h4>My dualband image just looks red</h4>"
       "<p>That's raw narrowband data from the dualband filter — see the Dualband topic. Stretch "
       "it as usual, then use <b>Narrowband…</b> to bring the oxygen out as teal. If you still "
       "have the raw subs, <b>Ha/OIII…</b> re-stacks them into a master that keeps more of that "
       "oxygen in the first place.</p>"
       "<h4>A tool isn't detected</h4>"
       "<p>Open <b>Settings</b>, set the path to the program, and press <b>Test</b>. GraXpert is "
       "required; RC-Astro is optional (steps fall back to free methods without it).</p>"
       "<h4>The log shows a change amount</h4>"
       "<p>The Δ% in the log estimates how much each step changed the visible image — a quick "
       "sanity check that a step did what you expected.</p>"),
)

TOPICS: dict[str, HelpTopic] = {t.id: t for t in _TOPIC_LIST}


SECTIONS: tuple[HelpSection, ...] = (
    HelpSection("Getting Started", ("getting-started",)),
    HelpSection("Concepts", ("linear-vs-stretched", "dualband", "step-order", "history", "readout")),
    HelpSection("The Steps", ("crop", "background", "color", "deconvolution", "stretch",
                              "recover_core", "levels", "curves", "saturation",
                              "green_fringe", "noise_sharpen", "local_contrast",
                              "star_reduction", "enhancements", "export")),
    HelpSection("Tools", ("tools", "auto-enhance", "plate-solve", "star_spikes", "narrowband",
                          "color_balance")),
    HelpSection("Sharing & Projects", ("share", "upscale", "saved-projects", "provenance")),
    HelpSection("Stacking & Ha/OIII", ("stacking", "haoiii")),
    HelpSection("Recipes & Batch", ("recipes",)),
    HelpSection("Troubleshooting", ("troubleshooting",)),
)
